name: Build and push image Aliyun

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Aliyun ACR
        run: |
          echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login \
            --username "${{ secrets.ALIYUN_
